### PR TITLE
Components and redux tests with Jest and Enzyme

### PR DESCRIPTION
**Pull request by brascene**
I could probably write more tests for Clicker component, e.g. for click increment action, and for tracking changes in the store, but it can be done later, I've made this request just to have something already done. :)

### CODE REVIEW

**Comment by levsthings** [comment]
Thanks for the PR! Test cases are solid, if you feel like adding more, please feel free to do so.

One question:
Is there any specific reason for using `chai`s assertions? Couldn't the same be achieved with assertions from `jest`?

**Comment by brascene** [comment]
@levsthings no specific reason for `chai` at all, it can all be done with `jest`, you can see that at one place I'm asserting with `to.be.equal` and on the other with `.equal`, no reason for this except I wanted to play a little bit with `chai` when testing component's properties, nested objects etc. But we can remove it later and leave only `jest` :)

**Comment by levsthings** [comment]
Yeah I've noticed that, I was curious maybe you had a specific reason for choosing `chai`s assertments in some cases. I want the test tooling to be as simple as possible so that it'll encourage users start testing right away.

Also did you have problems with the babel settings? I see that you added `regenerator-runtime` and `babel-preset-es2015`.:

We have the newer `babel-plugin-transform-runtime` installed already and setup in `.babelrc.js` and it should transform with these settings are passed:

```javascript
  "plugins": [
    ["transform-runtime", {
      "helpers": false, // defaults to true 
      "polyfill": false, // defaults to true 
      "regenerator": true, // defaults to true 
      "moduleName": "babel-runtime"
    }]
  ]
}`

And for `babel-preset-es2015`, it's no longer recommended to use that, that's why we're using `babel-preset-env`.

**Comment by brascene** [comment]
Regarding `chai`, I have some experience with it so it was my first choice for some assertions, but I had problem with using chai's expect and jest expect in the same test, that is, if I'm running `.toMatchSnapshot` then error occurs because `chai` doesn't contain it. I've also deleted some test with properties in redux store, but I didn't delete chai import, that's all.

And yes, regarding `babel`, I've had issues with running the tests so I imported `es2015` to include it in env-test presets, but issues weren't solved until I made babel file as `.babelrc`, without `.js`. I couldn't figure out where were problems with it, so I've copied all your plugins for _dev_ and _prod_ inside .babelrc just to keep it there.

**Comment by levsthings** [comment]
I think I see what the problem is with `babel`. I'm using `.babel.rc.js` to dynamically provide some settings to Webpack. But Jest is totally unaware of that file, it wants to see a `.babelrc` to start testing. As far as I know, there's no way to point to a custom babel file for Jest. I'll need to figure that one out.

**Comment by levsthings** [comment]
This should fix the issue.

**Pull request closed without merging**
